name: shabbos_app
description: "Shabbos!! - Shabbat & Yom Tov Candle Lighting Times"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  http: ^1.6.0
  flutter_local_notifications: ^19.5.0
  audioplayers: ^6.5.1
  shared_preferences: ^2.5.3
  permission_handler: ^12.0.1
  timezone: ^0.10.1
  android_alarm_manager_plus: ^4.0.4
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#1A1A1A"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/sounds/
